### PR TITLE
Added compatibility with OpenSSL 3+

### PR DESCRIPTION
**Pull request by frankmorgner**
currently untested

fixes [#12 ](https://github.com/OpenSC/pam_p11/issues/21)

### CODE REVIEW

**Comment by Polynomial-C** [comment]
Compile-tested with `openssl-1.1.1n` and `openssl-3.0.2` and both was successful. Didn't runtime test it though as I don't have a proper setup at hand right now.

**Comment by frankmorgner** [comment]
successfully tested with openssl 1.1.1 and oopenssl 3.0

**Comment by frankmorgner** [comment]
The better question would be "how does you public key look like?" so that it can be fixed. I tested pubkeys in X.509 certs.

**Comment by popovec** [comment]
I can confirm the problem with the RSA key... it will be solved with the patch below (tested against openssl 1.1.1n):
`````
diff --git a/src/match_openssh.c b/src/match_openssh.c
index fb59308..40478c0 100644
--- a/src/match_openssh.c
+++ b/src/match_openssh.c
@@ -63,7 +63,7 @@ int RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d)
 
 #endif
 
-static EVP_PKEY *init_evp_pkey_rsa(BIGNUM *rsa_e, BIGNUM *rsa_n)
+static EVP_PKEY *init_evp_pkey_rsa(BIGNUM *rsa_n, BIGNUM *rsa_e)
 {
        EVP_PKEY *key = NULL;
 
`````

**Comment by popovec** [comment]
I will prepare PR. I will try to add some functional test to the CI (using softhsm or some other pkcs#11 module).

**Pull request merged**
